### PR TITLE
Changes all attributes, except for the target, to arrays

### LINKED ISSUE #60: The 'class' attribute: as array or as string?
Hi! 
~~~I understand that you assign the value of the attribute 'class' for link as a string, but I cannot find where it in the code. :(~~~
I was looking for it because I added In my `THEME_preprocess_menu` this attributes as array and got this error `Error: [] operator not supported for strings` after enabling module `menu_link_attributes'

I used this code:
```   
$attrs = $item['url']->getOption('attributes');
// Error on this line and $attrs['class'] = "btn btn-primary text-light"; (I was set it on the menu option)
$attrs['class'][] = 'nav-link'; 
```
I'm not sure that I assign the attribute class correctly as an array, but stackoverflow says so :)

### PR DESCRIPTION
**Pull request by alexd73**
Fixes #60

### CODE REVIEW

**Review by CARECOORD — APPROVED** [review]

**Review by tallytarik — APPROVED** [review]
Fixes #60 

Confirmed the module now works with link_trail_by_path, which previously threw an error.

**Comment by stefan-korn** [comment]
+1 for bringing this in. Without this PR, there is WSOD in Radix theme (and maybe others too), see https://www.drupal.org/project/radix/issues/3086685

**Comment by jcnventura** [comment]
As mentioned in https://github.com/yannickoo/menu_link_attributes/issues/60#issuecomment-634971246, there's no reason to single out target.

**Comment by yannickoo** [comment]
_This issue has been moved to Drupal.org – [#3199777](https://www.drupal.org/project/menu_link_attributes/issues/3199777)_

**Pull request closed without merging**
